### ISSUE TITLE
Create Cluster Error

### ISSUE THREAD

**Issue by liyongxian** [tkestack/kstone#17]
Hi
   I install the kstone successfully,but when I create cluster,its UI does not show,and it is wrong.Thanks. 
![image](https://user-images.githubusercontent.com/18571576/145705751-75c5ba46-216b-4afe-ab6a-e9e740f59181.png)

**Comment by liyongxian** [comment]
API log:
![image](https://user-images.githubusercontent.com/18571576/145705884-778495be-04f1-4dcb-bef8-abe6e017dc8f.png)
dashboard log:
![image](https://user-images.githubusercontent.com/18571576/145705918-5cf1c5f3-a856-4133-bed2-7e0eaa8cf79a.png)

**Comment by tangcong** [comment]
What is your environment? If you don’t use tke, you need to configure ingress rules, refer to pr #16 .

**Comment by liyongxian** [comment]
Thanks. The environment  is bare k8s cluster environments.I access it by NodePort,Not by ingress. How can I do.

**Comment by liyongxian** [comment]
I want to create Etcd cluster by CRD of Etcd. Can you provide one Example.Thanks.

**Comment by liyongxian** [comment]
I use Ingress,and Its rules is:
![image](https://user-images.githubusercontent.com/18571576/145707438-9ef100b6-cb51-4723-aa86-93f3d00e097f.png)
But,can not access by google IE.
![image](https://user-images.githubusercontent.com/18571576/145707410-ac8f1d2f-4273-4bd3-8b3b-fb462d94bf3f.png)

**Comment by lianghao208** [comment]
@liyongxian 
The ingress rule:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kstone-ingress
  namespace: kstone
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kstone-dashboard
                port:
                  number: 80
          - path: /apis
            pathType: Prefix
            backend:
              service:
                name: kstone-dashboard-api
                port:
                  number: 80
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: kstone-grafana
                port:
                  number: 80

```
